# Generated by Django 4.2.5 on 2023-10-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='React',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='uploads/images/default.png', upload_to='uploads/images')),
                ('full_name', models.TextField(max_length=30)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('password', models.TextField(max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'React',
            },
        ),
    ]
