# Generated by Django 4.2.5 on 2023-10-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='uploads/images/default.png', upload_to='uploads/images')),
                ('title', models.TextField(max_length=30)),
                ('subtitle', models.TextField(max_length=30)),
                ('content', models.TextField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Blog',
            },
        ),
    ]
