# Generated by Django 4.2.5 on 2023-10-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='react',
            options={'verbose_name_plural': 'React'},
        ),
        migrations.RenameField(
            model_name='react',
            old_name='employee',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='react',
            name='department',
        ),
        migrations.AddField(
            model_name='react',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='react',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
