# Generated by Django 4.2.5 on 2023-10-10 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='react',
            options={'verbose_name_plural': 'React'},
        ),
    ]
