# Generated by Django 4.2.5 on 2023-10-17 19:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_brickwork_costestimation_designing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costestimation',
            name='labor_costs',
        ),
        migrations.AlterField(
            model_name='costestimation',
            name='structure',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
